### ISSUE TITLE
Lack of trailing slash should *NOT* stop recursion

### ISSUE THREAD

**Issue by ezarko** [vti/text-gitignore#2]
https://github.com/vti/text-gitignore/blob/347eb343dca19a995f02e6d291e62e5b18dcd52e/lib/Text/Gitignore.pm#L53

Perhaps:
```
$pattern .= '(\/|$)' unless $pattern =~ m{\/$};
```

**Comment by vti** [comment]
Could you provide a test case?

**Comment by ezarko** [comment]
```
mkdir foo
touch foo/bar
touch foo/baz
```
Put `/foo` in .gitignore.

**Comment by vti** [comment]
If you look into `t/` directory, there are lots of test cases for every situation. If you could just create a test that reproduces the problem, it would help a lot. Thanks!

**Comment by ezarko** [comment]
@vti sent a pull request with the added tests and the fix applied.  TravisCI seems to be acting up.
